# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07dd6fb358eca6979e437ce743f70e367be4beb94d692d6151f62fac512232c582af3cd191c377f55c856f88f680c10e31db69da1ad22527bf3cdd4d34f0206d

test:
  secret_key_base: 6df8e4f54b22166506cd98c808bd84ab87170e09b3f6994d6dc30edbd57c2c53a61c07b159a9abd728cd06a27bffae9f3518212c79c5d5569460d5a14d299adf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
